---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "trgt_merge"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::trgt=1.2.0"
